### PR TITLE
armani: Update jpeg decoder blobs for M

### PR DESCRIPTION
**Pull request by TheStrix**

### CODE REVIEW

**Comment by onano** [comment]
source of blobs?

**Comment by TechExhibeo** [comment]
@onano
https://github.com/TheMuppets/proprietary_vendor_motorola/tree/cm-13.0/msm8226-common

He has the souce in the commit message 🙌

**Comment by onano** [comment]
whops my bad.

**Comment by TechExhibeo** [comment]
These blobs are tested too 😀

**Comment by fefifofum** [comment]
Did you test if hdr works properly with the new blobs?

**Comment by TheStrix** [comment]
@fefifofum Yes, it captures properly on HDR mode as well.

**Comment by TheStrix** [comment]
Build: https://www.androidfilehost.com/?fid=24349802275799449
This contains just these 2 changes and rest all same as yours. You can test.

**Comment by fefifofum** [comment]
Ok, I'll cherry-pick your commit and change a couple of details.

**Pull request closed without merging**
